# Generated by Django 6.0 on 2025-12-14 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 2, 55, 37, 51990, tzinfo=datetime.timezone.utc)),
        ),
    ]
